[package]
name = "promise-future-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "promise_rs"

[[bin]]
name = "promise_rs"
path = "src/main.rs"
